services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: medinote-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  mysql:
    image: mysql:8.0
    container_name: medinote-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  qdrant_storage:
  mysql_data: