"""create disease master table

Revision ID: 0502c6dab597
Revises: a552d302161d
Create Date: 2026-08-29 14:16:42.314156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0502c6dab597'
down_revision: Union[str, Sequence[str], None] = 'a552d302161d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_master',
    sa.Column('disease_code', sa.String(length=20), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('disease_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_master')
    # ### end Alembic commands ###
