"""add test memo to chat rooms

Revision ID: 2b1e7e95be0f
Revises: 31f36be898a8
Create Date: 2026-08-27 12:22:16.573084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b1e7e95be0f'
down_revision: Union[str, Sequence[str], None] = '31f36be898a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'test_memo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('test_memo', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
