"""add test memo to chat rooms

Revision ID: 31f36be898a8
Revises: e325f17a2455
Create Date: 2026-08-27 12:21:50.344119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f36be898a8'
down_revision: Union[str, Sequence[str], None] = 'e325f17a2455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('test_memo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'test_memo')
    # ### end Alembic commands ###
